# https://projecteuler.net/problem=2

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fib(limit):
    a, b = 0, 1
    for _ in range(limit):
        yield b
        a, b = b, (a + b)


def even_fib(numbers):
    return filter(lambda x: x % 2 != 0, numbers)


if __name__ == "__main__":
    for i in even_fib(fib(10)):
        print(i)
